import "./components/choices";
import "./components/swiper";
import "./components/tabs";
import "./components/modal";
import "./components/dynamic_adapt";
import "./components/smooth-scroll";
import "./components/range-slider";
import "./components/accordion";
import "./components/filter-menu";
